/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author gerso
 */
public class Jf_Vehiculo extends javax.swing.JFrame {

    /**
     * Creates new form Jf_Vehiculo
     */
    DefaultTableModel t_registro;
    public Jf_Vehiculo() {
        initComponents();
        setLocationRelativeTo(null);
       t_registro = new DefaultTableModel(); 
       String encabezado[] = {
        "Medio trasnporte","Matricula","Marca","Asientos",
        "Serie","Tipo","Modelo","Color","Chasis","Cilindros",
        "Motor","Transmision","Velocidades","Traccion","Cabinas",
        "motores","Rotores","Turbinas","Helices"};
       t_registro.setColumnIdentifiers(encabezado);
       tbl_registro.setModel(t_registro);
       
       
       
       
    }
    
    public void agregar (){
        
        String datos[] = new String[19];
        datos [0] = this.jcb_medioTransporte.getSelectedItem().toString();
        datos [1] = this.txt_matricula.getText();
        datos [2] = this.jcb_marca.getSelectedItem().toString();
        datos [3] = this.txt_cantidadAsientos.getText();
        datos [4] = this.txt_serie.getText();
        datos [5] = this.jcb_tipo.getSelectedItem().toString();
        datos [6] = this.txt_modelo.getText();
        datos [7] = this.jcb_color.getSelectedItem().toString();
        datos [8] = this.txt_chasis.getText();
        datos [9] = this.jcb_nCilinddros.getSelectedItem().toString();
        datos [10]= this.jcb_motor.getSelectedItem().toString();
        datos [11] = this.jcb_transmision.getSelectedItem().toString();
        datos [12] = this.jcb_velocidades.getSelectedItem().toString();
        datos [13] = this.jcb_traccion.getSelectedItem().toString();
        datos [14] = this.jcb_numeroCabinas.getSelectedItem().toString();
        datos [15] = this.jcb_numeroMotores.getSelectedItem().toString();
        datos [16] = this.jcb_rotores.getSelectedItem().toString();
        datos [17] = this.jcb_numeroTurbinas.getSelectedItem().toString();
        datos [18] = this.jcb_numeroHelices.getSelectedItem().toString();
        t_registro.addRow(datos);
        
        this.jcb_medioTransporte.requestFocus();
    
    }
    
    public void limpiar (){
    this.jcb_medioTransporte.setSelectedIndex(0);
    this.txt_matricula.setText("");
    this.jcb_marca.setSelectedIndex(0);
    this.txt_cantidadAsientos.setText("");
    this.txt_serie.setText("");
    this.jcb_tipo.setSelectedIndex(0);
    this.txt_modelo.setText("");
    this.jcb_color.setSelectedIndex(0);
    this.txt_chasis.setText("");
    this.jcb_nCilinddros.setSelectedIndex(0);
    this.jcb_motor.setSelectedIndex(0);
    this.jcb_transmision.setSelectedIndex(0);
      this.jcb_velocidades.setSelectedIndex(0);
      this.jcb_traccion.setSelectedIndex(0);
      this.jcb_numeroCabinas.setSelectedIndex(0);
      this.jcb_numeroMotores.setSelectedIndex(0);
      this.jcb_rotores.setSelectedIndex(0);
      this.jcb_numeroTurbinas.setSelectedIndex(0);
      this.jcb_numeroHelices.setSelectedIndex(0);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbl_nregistro = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jcb_medioTransporte = new javax.swing.JComboBox<>();
        lbl_medioTransporte = new javax.swing.JLabel();
        lbl_matricula = new javax.swing.JLabel();
        txt_matricula = new javax.swing.JTextField();
        lbl_marca = new javax.swing.JLabel();
        jcb_marca = new javax.swing.JComboBox<>();
        lbl_serie = new javax.swing.JLabel();
        lbl_tipo = new javax.swing.JLabel();
        jcb_tipo = new javax.swing.JComboBox<>();
        lbl_modelo = new javax.swing.JLabel();
        txt_modelo = new javax.swing.JTextField();
        lbl_cantidadAsientos = new javax.swing.JLabel();
        txt_cantidadAsientos = new javax.swing.JTextField();
        lbl_color = new javax.swing.JLabel();
        jcb_color = new javax.swing.JComboBox<>();
        txt_codigoChasis = new javax.swing.JLabel();
        txt_chasis = new javax.swing.JTextField();
        txt_serie = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        txt_cilindros = new javax.swing.JLabel();
        txt_transmicion = new javax.swing.JLabel();
        lbl_motor = new javax.swing.JLabel();
        jcb_nCilinddros = new javax.swing.JComboBox<>();
        jcb_transmision = new javax.swing.JComboBox<>();
        txt_velocidades = new javax.swing.JLabel();
        jcb_velocidades = new javax.swing.JComboBox<>();
        txt_traccion = new javax.swing.JLabel();
        jcb_motor = new javax.swing.JComboBox<>();
        jcb_traccion = new javax.swing.JComboBox<>();
        txt_numeroMotores = new javax.swing.JLabel();
        jcb_numeroMotores = new javax.swing.JComboBox<>();
        txt_numeroCabinas = new javax.swing.JLabel();
        jcb_numeroCabinas = new javax.swing.JComboBox<>();
        txt_numeroTurbinas = new javax.swing.JLabel();
        jcb_numeroTurbinas = new javax.swing.JComboBox<>();
        txt_numeroHelices = new javax.swing.JLabel();
        jcb_numeroHelices = new javax.swing.JComboBox<>();
        txt_rotores = new javax.swing.JLabel();
        jcb_rotores = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbl_registro = new javax.swing.JTable();
        btn_agregar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lbl_nregistro.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lbl_nregistro.setText("Nuevo Registro");

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Informacion comercial", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 12), new java.awt.Color(51, 153, 255))); // NOI18N

        jcb_medioTransporte.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-Seleccionar-", "Avion", "Carro", "Helicopero", "Moto" }));

        lbl_medioTransporte.setText("Medio de transporte:");

        lbl_matricula.setText("Matricula:");

        txt_matricula.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_matriculaActionPerformed(evt);
            }
        });

        lbl_marca.setText("Marca:");

        jcb_marca.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-Seleccionar-", "Boeing 747", "Airbus A330", "McDonnell Douglas", "Toyota", "Honda", "BMW", "Yamaha", "Suzuki" }));

        lbl_serie.setText("Serie:");

        lbl_tipo.setText("Tipo:");

        jcb_tipo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-Seleccionar-", "Militar", "Comercial", "Suv", "Sedan", "Hatchback", "Trail", "Pasola", " " }));

        lbl_modelo.setText("Modelo:");

        lbl_cantidadAsientos.setText("Cantidad de asientos:");

        lbl_color.setText("Color:");

        jcb_color.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-Seleccionar-", "Negro", "Azul", "Rojo", "Blanco" }));

        txt_codigoChasis.setText("Codigo Chasis:");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(9, 9, 9)
                        .addComponent(lbl_medioTransporte))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbl_modelo)
                            .addComponent(lbl_cantidadAsientos, javax.swing.GroupLayout.Alignment.TRAILING))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(txt_modelo)
                    .addComponent(jcb_medioTransporte, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txt_cantidadAsientos, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(40, 40, 40)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbl_matricula)
                    .addComponent(lbl_serie)
                    .addComponent(lbl_color))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 27, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jcb_color, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txt_matricula)
                    .addComponent(txt_serie, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbl_marca)
                    .addComponent(lbl_tipo)
                    .addComponent(txt_codigoChasis))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jcb_marca, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_chasis)
                    .addComponent(jcb_tipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(txt_matricula, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(61, 61, 61)
                            .addComponent(jcb_color, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(lbl_marca)
                                .addComponent(jcb_marca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(15, 15, 15)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(lbl_tipo)
                                .addComponent(jcb_tipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(24, 24, 24)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(txt_codigoChasis)
                                .addComponent(txt_chasis, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jcb_medioTransporte, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(lbl_matricula))
                            .addGap(18, 18, 18)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(txt_cantidadAsientos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lbl_cantidadAsientos))
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(lbl_serie)
                                        .addComponent(txt_serie, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGap(3, 3, 3)))
                            .addGap(18, 18, 18)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(txt_modelo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(lbl_color))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(lbl_medioTransporte)
                        .addGap(64, 64, 64)
                        .addComponent(lbl_modelo)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Infromacion mecanica", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 12), new java.awt.Color(51, 153, 255))); // NOI18N

        txt_cilindros.setText("Numero de cilindros:");

        txt_transmicion.setText("Transmision:");

        lbl_motor.setText("Motor:");

        jcb_nCilinddros.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "---", "4", "6", "8", "12" }));

        jcb_transmision.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "---", "Manual", "Automatica" }));

        txt_velocidades.setText("Velocidades:");

        jcb_velocidades.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "---", "1", "5", "6", " " }));

        txt_traccion.setText("Traccion:");

        jcb_motor.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "---", "1.5", "1.8", "2.0", "2.5", "300cc", "250cc", "375HP", "200HP", " " }));
        jcb_motor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcb_motorActionPerformed(evt);
            }
        });

        jcb_traccion.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "---", "Delantera", "Delantera y Trasera", " ", " " }));

        txt_numeroMotores.setText("Numero de motores:");

        jcb_numeroMotores.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "---", "1", "2", "3", "4", " " }));

        txt_numeroCabinas.setText("Numero de Cabinas:");

        jcb_numeroCabinas.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "---", "1", "2", "3", "4", "5", " " }));

        txt_numeroTurbinas.setText("Numero de Turbinas:");

        jcb_numeroTurbinas.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "---", "4", "6" }));

        txt_numeroHelices.setText("Numero de Helices:");

        jcb_numeroHelices.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "---", "1", "2", "3", "4" }));

        txt_rotores.setText("Rotores");

        jcb_rotores.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "---", "1", "2", "3", " " }));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txt_cilindros)
                    .addComponent(txt_velocidades)
                    .addComponent(txt_numeroMotores)
                    .addComponent(txt_numeroHelices))
                .addGap(34, 34, 34)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jcb_nCilinddros, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jcb_numeroMotores, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jcb_numeroHelices, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jcb_velocidades, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(48, 48, 48)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbl_motor)
                    .addComponent(txt_traccion)
                    .addComponent(txt_rotores))
                .addGap(24, 24, 24)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jcb_rotores, 0, 88, Short.MAX_VALUE)
                    .addComponent(jcb_traccion, 0, 1, Short.MAX_VALUE)
                    .addComponent(jcb_motor, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txt_transmicion)
                    .addComponent(txt_numeroCabinas)
                    .addComponent(txt_numeroTurbinas))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jcb_transmision, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jcb_numeroCabinas, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jcb_numeroTurbinas, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(101, 101, 101))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(13, 13, 13)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_cilindros)
                    .addComponent(jcb_nCilinddros, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl_motor)
                    .addComponent(jcb_motor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_transmicion)
                    .addComponent(jcb_transmision, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_velocidades)
                    .addComponent(jcb_velocidades, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_traccion)
                    .addComponent(jcb_traccion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_numeroCabinas)
                    .addComponent(jcb_numeroCabinas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_numeroMotores)
                    .addComponent(jcb_numeroMotores, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_numeroTurbinas)
                    .addComponent(jcb_numeroTurbinas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txt_rotores)
                        .addComponent(jcb_rotores)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_numeroHelices)
                    .addComponent(jcb_numeroHelices, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        tbl_registro.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(tbl_registro);

        btn_agregar.setText("Agregar");
        btn_agregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_agregarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 694, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1450, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btn_agregar, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addComponent(lbl_nregistro)))
                .addContainerGap(33, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbl_nregistro)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addComponent(btn_agregar)
                .addGap(33, 33, 33)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 243, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(29, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jcb_motorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcb_motorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jcb_motorActionPerformed

    private void btn_agregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_agregarActionPerformed
        // TODO add your handling code here:
        
        agregar ();
        limpiar();
       
    }//GEN-LAST:event_btn_agregarActionPerformed

    private void txt_matriculaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_matriculaActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_txt_matriculaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Jf_Vehiculo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Jf_Vehiculo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Jf_Vehiculo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Jf_Vehiculo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Jf_Vehiculo().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_agregar;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JComboBox<String> jcb_color;
    private javax.swing.JComboBox<String> jcb_marca;
    private javax.swing.JComboBox<String> jcb_medioTransporte;
    private javax.swing.JComboBox<String> jcb_motor;
    private javax.swing.JComboBox<String> jcb_nCilinddros;
    private javax.swing.JComboBox<String> jcb_numeroCabinas;
    private javax.swing.JComboBox<String> jcb_numeroHelices;
    private javax.swing.JComboBox<String> jcb_numeroMotores;
    private javax.swing.JComboBox<String> jcb_numeroTurbinas;
    private javax.swing.JComboBox<String> jcb_rotores;
    private javax.swing.JComboBox<String> jcb_tipo;
    private javax.swing.JComboBox<String> jcb_traccion;
    private javax.swing.JComboBox<String> jcb_transmision;
    private javax.swing.JComboBox<String> jcb_velocidades;
    private javax.swing.JLabel lbl_cantidadAsientos;
    private javax.swing.JLabel lbl_color;
    private javax.swing.JLabel lbl_marca;
    private javax.swing.JLabel lbl_matricula;
    private javax.swing.JLabel lbl_medioTransporte;
    private javax.swing.JLabel lbl_modelo;
    private javax.swing.JLabel lbl_motor;
    private javax.swing.JLabel lbl_nregistro;
    private javax.swing.JLabel lbl_serie;
    private javax.swing.JLabel lbl_tipo;
    private javax.swing.JTable tbl_registro;
    private javax.swing.JTextField txt_cantidadAsientos;
    private javax.swing.JTextField txt_chasis;
    private javax.swing.JLabel txt_cilindros;
    private javax.swing.JLabel txt_codigoChasis;
    private javax.swing.JTextField txt_matricula;
    private javax.swing.JTextField txt_modelo;
    private javax.swing.JLabel txt_numeroCabinas;
    private javax.swing.JLabel txt_numeroHelices;
    private javax.swing.JLabel txt_numeroMotores;
    private javax.swing.JLabel txt_numeroTurbinas;
    private javax.swing.JLabel txt_rotores;
    private javax.swing.JTextField txt_serie;
    private javax.swing.JLabel txt_traccion;
    private javax.swing.JLabel txt_transmicion;
    private javax.swing.JLabel txt_velocidades;
    // End of variables declaration//GEN-END:variables
}
